# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5b75e615d0a3bb64ffc3c2ddf756fe95dd32b6d1db861365cae8c713fdfe3d15a0751318eeb8832fac532129cfd2194fe0e69599af96b773ab5603b77b5867

test:
  secret_key_base: cc7a5ace672aea3801f5663914bb8abb4809b6f768e9472126e47f801c555414c4fa573d14ea685205561e61e6fd7db17ae1b64a8c8d050ead53eb3bb7101cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
